name: "🐛 Bug report"
description: "Something isn’t working?  Help us fix it."
title: "[Bug] <short description>"
labels: ["bug", "needs-triage"]
assignees: []

body:
  # -----  Quick self-triage  -----
  - type: markdown
    attributes:
      value: |
        **Thanks for opening a report!**

        Most problems are solved by one of the checks below.  
        Please tick **every box** before continuing.

        - [ ] I searched **open** and **closed** issues for something similar.  
        - [ ] I’m on the **latest** release/tag of ATAK-Maps.  
        - [ ] I purged or re-downloaded the map/layer cache.  
        - [ ] For remote layers, I confirmed the URL works in a browser (tiles/WMS/KML reachable).  
        - [ ] I disabled other plugins/maps to rule out conflicts.  
        - [ ] I can reproduce the problem **consistently** with the steps I’ll describe below.

  # -----  Environment  -----
  - type: input
    id: atak_maps_version
    attributes:
      label: ATAK-Maps version / commit
      placeholder: "v1.2.1  (or commit SHA)"
    validations:
      required: true

  - type: input
    id: tak_client_version
    attributes:
      label: TAK client / server version
      placeholder: "ATAK-CIV 5.4.0.9 (24009d04), iTAK 2.12.0"
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Device & OS
      description: "Phone/tablet model, Android/iOS version, emulator, etc."
      placeholder: |
        • Device: Samsung Tab Active 3  
        • OS: Android 14 / OneUI 6.1
    validations:
      required: false

  # -----  Problem details  -----
  - type: textarea
    id: what_happened
    attributes:
      label: What happened?
      description: "Describe the bug and what you *expected* to happen."
      placeholder: |
        When I enable the FEMA Flood layer the app crashes after ~10 s
        instead of displaying polygons.
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Open Layers → “Google Hybrid”
        2. Toggle the layer on  
        3. Zoom to 1:50 000  
        4. Observe blank tiles
    validations:
      required: true

  - type: dropdown
    id: reproducibility
    attributes:
      label: How often can you reproduce the issue?
      options:
        - Every time
        - Often ( >75% )
        - Sometimes ( 25–75% )
        - Rarely ( <25% )
        - Unable to reproduce now
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output (optional)
      description: "Paste stack-traces or console errors between ``` ```."
      render: shell
    validations:
      required: false

  - type: textarea
    id: extra
    attributes:
      label: Anything else?
      description: "Screenshots, the faulty XML/TMS URL, ideas for a fix, etc."
    validations:
      required: false
