# Triggers whenever an XML map file is pushed to `master`
# (or whenever the workflow is run manually).
#
# 1. Zips every *.xml map into dist/atak-maps.zip
# 2. Runs semantic-release to:
#      • calculate the next SemVer
#      • tag the commit
#      • create / update the GitHub Release
#      • attach the ZIP as a release asset
#
# NOTE: .releaserc.json must live at repo root
#       and list the @semantic-release/github plugin
#       with   "path": "dist/atak-maps.zip"
#       (label can stay versioned).

name: Map Release

on:
  push:
    branches: [master]
    paths: "**/*.xml"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    # Needed so the action can create tags/releases.
    permissions:
      contents: write
      issues:   write   # still off by default via failComment:false

    steps:
      # -- Checkout full history so semantic-release can find previous tags
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # -- Build ZIP of all XML map sources
      - name: Build ZIP of maps
        run: |
          mkdir -p dist
          zip -r dist/atak-maps.zip $(git ls-files '*.xml')

      # -- Run semantic-release (wrapper bundles the CLI + plugins)
      - name: semantic-release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
