# Triggers whenever an XML map file hits `master` (or on demand).
# Creates/updates a SemVer tag + GitHub Release and attaches a ZIP of all maps.
name: Map Release

on:
  push:
    branches: [master]
    paths:
      - "**/*.xml"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      # needed for semantic-release to tag and publish the Release
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # full history → proper version analysis

      # Package every XML map into one artifact
      - name: Build ZIP of maps
        run: |
          mkdir -p dist
          zip -r dist/atak-maps.zip $(git ls-files '*.xml')

      # Run semantic-release (wrapper bundles the CLI for you)
      - name: semantic-release
        uses: cycjimmy/semantic-release-action@v4
        with:
          branch: master
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            "@semantic-release/github"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
