# Triggers whenever an XML map file hits `master` (or on demand).
# Creates/updates a SemVer tag + GitHub Release and attaches a ZIP of all maps.
name: Map Release

on:
  push:
    branches: [master]
    paths: "**/*.xml"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    # Needed for tagging/releases (contents) and, if you re-enable failComment,
    # issue creation (issues).
    permissions:
      contents: write
      issues: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # full history → correct version calculation

      - name: Build ZIP of maps
        run: |
          mkdir -p dist
          zip -r dist/atak-maps.zip $(git ls-files '*.xml')

      - name: semantic-release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
